### ISSUE TITLE
When player stayed in house, house information accordion indicates buying

### ISSUE THREAD

**Issue by averbraeck** [averbraeck/housinggame-player#43]
The house accordion (number 3) indicates buying a house when the player stayed:

![image](https://github.com/averbraeck/housinggame-player/assets/13779793/592ae8c3-37cd-4d20-b679-368737a7b383)

**Comment by vjcortesa** [comment]
the player: 
- [ ] Is misled by the first sentence: please change it depending on whether the player bought or stayed in the same house.
- [ ] can not easily notice what this text is about: Add headers to structure the content, namely House choice, Mortgage payment and satisfaction points.
- [ ] misses money later on because he did not notice that he/she made two payments on this round: Add that "This round, you paid 7k"
- [ ] The list of items is longer if the above is added: One row can be removed by integrating the house address into the first sentence. 
- [ ] Question: Is there a negative satisfaction change of - o + every time I decide to stay in the same house with a preferred rating below or above? The first version of the rules game was written as follows: 
"A one-time satisfaction change in your satisfaction score. Later in the house market step, if the house you bought has a lower/higher rating than the preferred house rating. If you decide to relocate, you will compare your previously owned house (rating) with your new house (rating)". However, it makes sense to lose satisfaction every round as long as you remain in the same house.
![240224_Adjustments for clarity to your house confirmation](https://github.com/averbraeck/housinggame-player/assets/8215750/cdbc76ef-a678-40d6-a6af-6b0564f90043)

**Comment by averbraeck** [comment]
New screen of a player who bought a house:

![image](https://github.com/averbraeck/housinggame-player/assets/13779793/e9350fc2-9159-4907-be18-48cf8919c666)

**Comment by averbraeck** [comment]
Effects of https://github.com/averbraeck/housinggame-common/issues/23 have been added to the house round information when staying.

**Comment by averbraeck** [comment]
New screen for a player who stayed in the same house WITHOUT satisfaction changes per round:

![image](https://github.com/averbraeck/housinggame-player/assets/13779793/f6fbce9e-8c3c-489b-a32b-5c8e3ef7b22e)

**Comment by averbraeck** [comment]
New screen for a player who stayed in the same house WITH satisfaction changes per round:

![image](https://github.com/averbraeck/housinggame-player/assets/13779793/f99352ff-1911-4043-93a0-a047350c1b17)

**Comment by averbraeck** [comment]
All tasks have been addressed.
