### ISSUE TITLE
News text in the player website do not match the text in the administration site

### ISSUE THREAD

**Issue by vjcortesa** [averbraeck/housinggame-player#53]
- [ ] The text in the player website do not match the text in the administration site. I was trying to adjust the news to make a 4 rounds game. When I realised the logic was not fully working, I forgot by mistake to change it back to its correct setting for a five rounds game. That's how I noticed the error.
- [ ] Once a news item, or a news effect is created in the administration site, can not be deleted

![240224_News adjustment in the player website](https://github.com/averbraeck/housinggame-player/assets/8215750/49f3d81b-dc8a-474a-a04d-b23496f86ab1)

**Comment by averbraeck** [comment]
DO NOT CHANGE A GAME THAT HAS BEEN PLAYED.

That is why the rounds or news messages cannot be deleted. By changing them, the entire game becomes inconsistent and unstable.

**Comment by averbraeck** [comment]
The reason the text did not show up was because the scenario played was "Without information", and the changed news was in the "With information" scenario. Any text change shows up:

![image](https://github.com/averbraeck/housinggame-player/assets/13779793/ac709394-2b93-401d-bb54-1c32f2f8574d)

![image](https://github.com/averbraeck/housinggame-player/assets/13779793/5ee3982c-b8b6-4ca7-9a50-050f03b363f8)
