### ISSUE TITLE
Check calculation of satisfaction points

### ISSUE THREAD

**Issue by averbraeck** [averbraeck/housinggame-player#61]
The calculation of the satisfaction points should be re-checked, especially for players who are in debt, live in a house under their required level, and who are prone to flooding. A new and enhanced overview of the satisfaction points should help in identifying any inconsistencies.

**Comment by vjcortesa** [comment]
The rules, stated as follows:
i.	River flooding: 2 six-sided dice are thrown by the facilitator or the players themselves. 
•	Damage: dice – protection (public + private): water volume you are unprotected for
•	Satisfaction: Damage (+ 1 if area flooded)
For example, you are unprotected if you have 2 damage due to the water volume. Therefore, one will get 3 satisfaction lost, equal to 1 for every damage plus the satisfaction penalty if the area is flooded
ii.	Rain flooding: 1 ten-sided dice is thrown by the facilitator.
•	Damage: If the dice number is higher than the protection of the area and the player does not have private protection against rain floods, the damage is 1, yes otherwise, 0, no. 
•	Satisfaction: same applies. There is no damage point if the area is flooded and one is protected from rain. Otherwise, there is 1 damage point. There is no additional satisfaction penalty if the area is flooded.

The overview on the satisfaction points can be improved as follows for the view summary at the end of each round
![image](https://github.com/averbraeck/housinggame-player/assets/8215750/9dd8fb83-89b4-4e53-9ab9-879ed91c0c05)

**Comment by averbraeck** [comment]
The screen shows a clear calculation now:

![image](https://github.com/user-attachments/assets/8591288d-7910-46f9-9a5f-b62dee84f5b6)
